### ISSUE TITLE
Kaltura Player Incompatible service

### ISSUE THREAD

**Issue by Quantizr** [vantezzen/skip-silence#136] opened 2023-02-25 23:58 UTC
What service is not compatible? (e.g. "Vimeo"): Kaltura Web Player

Can you provide a link to a specific video where this has occurred? (i.e. can you provide the link where this happend?):
University uses Kaltura Web Player embedded in Canvas, since the link requires login, here is a page where an example embed of Kaltura Web Player can be found http://player.kaltura.com/docs/

What is the exact problem that occurred? (e.g. "No sound detected" or "No video detected/icon is not green"): ...
Video is not sped up, even though video detected and sound detected

What version of Skip Silence are you using? (i.e. 1, 2 or 3. You can find this information by opening the popup, it should be right in the title):
v5.1.0

Do you have any other information that might be useful?:
Problem does not exist in v4.0.0

**Comment by WofWca** [comment] 2023-02-27 06:07
The link you provided is an HTTP-only. [Some web APIs don't work in non-secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts).
Is your uni's page served with HTTPS?
Also the page you linked does have a `<video>` element, it's not just a `<canvas>`.

**Comment by Quantizr** [comment] 2023-02-27 06:12
> The link you provided is an HTTP-only. [Some web APIs don't work in non-secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts). Is your uni's page served with HTTPS? Also the page you linked does have a `<video>` element, it's not just a `<canvas>`.

It is served with HTTPS, but the behavior on both the university page and the http-only page is the exact same. 

Sorry, I probably should have clarified what I meant, I understand its a video element, I meant that the webpage is on Instructure's Canvas platform.

**Comment by Quantizr** [comment] 2023-03-09 08:42
The problem stems from this line
https://github.com/vantezzen/skip-silence/blob/6ac09af6e4dd5c34e3fef30d0c940a7c027ce2c7/src/contents/lib/SpeedController.ts#L104

which returns 0 elements on a page with a Kaltura player

Replacing
https://github.com/vantezzen/skip-silence/blob/6ac09af6e4dd5c34e3fef30d0c940a7c027ce2c7/src/contents/lib/SpeedController.ts#L102-L117

with
```
  setPlaybackRate(rate: number) {
    inspectMediaElements((element: MediaElement) => {
      this.setPlaybackRateForElement(rate, element)
    })
  }
```

and adding an import statement for `inspectMediaElements` fixes the problem

I'll make a pull request with these changes

**Comment by WofWca** [comment] 2023-03-09 09:24
I think it's because the video element is inside an `<iframe>`. May be a duplicate of #23, not sure.

**Closed** 2023-03-10 15:34 UTC
Labels: incompatible service
