### ISSUE TITLE
Synchronisation Problem

### ISSUE THREAD

**Issue by SubGi** [vantezzen/skip-silence#53] opened 2021-06-04 11:33 UTC
**Describe the bug**
Video and Audio becomes out of sync after some time when using skip silence
**To Reproduce**
Can be tested on any video

**Expected behavior**
Everything should remain in sync throughout the video

**Desktop **
 - OS: [Windows 10]
 - Browser : Chrome
 - Skip Silence Version 3

**Comment by WofWca** [comment] 2021-06-04 11:36
Duplicate of #28

**Closed** 2021-06-04 13:52 UTC
Labels: bug
