### ISSUE TITLE
Double video

### ISSUE THREAD

**Issue by enes-kazazic** [vantezzen/skip-silence#11] opened 2020-06-06 10:22 UTC
I use chrome extension Local Media Player (i'll use "LMP" in further text) . Problem is that when I turn on your extension it plays video separately from the video playing on LMP. Even if I pause video on LMP, or turn off your extension, other video that is somehow duplicated continues. Also your extension doesn't  registry it, its just playing - I dont know where. This is happening after the new update, it was all fine before. 

If you can't fix it fast, or dont know how to, dont bother to do it, i'll use other player.

**Comment by vantezzen** [comment] 2020-06-07 17:59
Thank you for leaving this feedback. I could reproduce the bug you mentioned using local files.
The problem was with the new pre-buffer feature that wrongfully started playing without being muted.
I've now fixed this bug which will be published with the next version of this extension which should release in the next few days.

**Closed by vantezzen** 2020-06-07 17:59 UTC
