### ISSUE TITLE
feature request: give some numbers to sliders. 

### ISSUE THREAD

**Issue by techdough** [vantezzen/skip-silence#12] opened 2020-06-07 05:52 UTC
hard to tell when i slider what i am setting. if duration threshold had MS or volume threshold had some db then its easier to set and gauge what I am setting.

**Comment by vantezzen** [comment] 2020-06-07 17:55
The problem is that "Skip Silence" doesn't really use any normal units like decibels - it really only uses arbitraty values. I have however tried to add some labels to help get a sense of the current value of the sliders:

![Screenshot](https://user-images.githubusercontent.com/10333196/83976184-c5ac9880-a8f8-11ea-926b-d56bfa0a61f8.png)

This change will be released with the next update.

**Closed by vantezzen** 2020-06-07 17:55 UTC

**Comment by techdough** [comment] 2020-06-12 21:11
perfect looks good! very useful now!!!
